services:
  postgres:
    image: postgres:15
    container_name: ${CONTAINER_NAME}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - eureca_pgdata:/var/lib/postgresql/data
      - ./application/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  eureca_pgdata: