
import strawberry
from typing import List, Optional

@strawberry.type
class Estudante:
    matricula_do_estudante: Optional[str]
    codigo_do_curso: Optional[int]
    nome_do_curso: Optional[str]
    turno_do_curso: Optional[str]
    codigo_do_curriculo: Optional[int]
    campus: Optional[int]
    nome_do_campus: Optional[str]
    codigo_do_setor: Optional[int]
    nome_do_setor: Optional[str]
    estado_civil: Optional[str]
    genero: Optional[str]
    idade: Optional[str]
    situacao: Optional[str]
    motivo_de_evasao: Optional[str]
    periodo_de_evasao: Optional[str]
    forma_de_ingresso: Optional[str]
    periodo_de_ingresso: Optional[str]
    nacionalidade: Optional[str]
    local_de_nascimento: Optional[str]
    naturalidade: Optional[str]
    cor: Optional[str]
    deficiencias: Optional[List[str]]
    ano_de_conclusao_ensino_medio: Optional[int]
    tipo_de_ensino_medio: Optional[str]
    politica_afirmativa: Optional[str]
    prac_renda_per_capita_ate: Optional[float]
    creditos_do_cra: Optional[int]
    notas_acumuladas: Optional[float]
    periodos_completados: Optional[int]
    creditos_tentados: Optional[int]
    creditos_completados: Optional[int]
    creditos_isentos: Optional[int]
    creditos_falhados: Optional[int]
    creditos_suspensos: Optional[int]
    creditos_em_andamento: Optional[int]
    velocidade_media: Optional[float]
    taxa_de_sucesso: Optional[float]
    prac_atualizado: Optional[str]
    prac_atualizado_em: Optional[str]
    prac_cor: Optional[str]
    prac_quilombola: Optional[str]
    prac_indigena_aldeado: Optional[str]
    prac_deficiente: Optional[str]
    prac_deficiencias: Optional[List[str]]
    prac_deslocou_mudou: Optional[str]
    ufpb: Optional[str]


@strawberry.type
class EstudanteDisciplina:
    matricula_do_estudante: Optional[str]
    codigo_da_disciplina: Optional[int]
    nome_da_disciplina: Optional[str]
    periodo: Optional[str]
    turma: Optional[int]
    status: Optional[str]
    tipo: Optional[str]
    media_final: Optional[float]
    dispensas: Optional[str]

